version: 2

project_name: mumble-discord-bridge

before:
  hooks:
    - go mod tidy
    - go install github.com/google/go-licenses@latest

builds:
  - id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/mumble-discord-bridge
    env:
      - CGO_ENABLED=1
      - CC=gcc
    ldflags: "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser"
    flags:
      - -tags=netgo
    hooks:
      post:
        - cmd: go-licenses save ./cmd/mumble-discord-bridge --save_path="./dist/LICENSES"

  - id: linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/mumble-discord-bridge
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
    ldflags: "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser"
    flags:
      - -tags=netgo

checksum:
  name_template: "checksums.txt"

dockers:
  # We break the goreleaser pattern by not copying the build binary into the docker image.
  # Instead we use a two-stage build to create a static binary in the docker image.
  # The docker file uses Alpine (musl) while we build the binary for glibc.
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "stieneee/mumble-discord-bridge:{{ .Version }}-amd64"
      - "ghcr.io/stieneee/mumble-discord-bridge:{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/stieneee/mumble-discord-bridge"

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - "stieneee/mumble-discord-bridge:{{ .Version }}-arm64"
      - "ghcr.io/stieneee/mumble-discord-bridge:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/stieneee/mumble-discord-bridge"

docker_manifests:
  - name_template: stieneee/mumble-discord-bridge:latest
    image_templates:
      - stieneee/mumble-discord-bridge:{{ .Version }}-amd64
      - stieneee/mumble-discord-bridge:{{ .Version }}-arm64
  - name_template: stieneee/mumble-discord-bridge:{{ .Version }}
    image_templates:
      - stieneee/mumble-discord-bridge:{{ .Version }}-amd64
      - stieneee/mumble-discord-bridge:{{ .Version }}-arm64
  - name_template: ghcr.io/stieneee/mumble-discord-bridge:latest
    image_templates:
      - ghcr.io/stieneee/mumble-discord-bridge:{{ .Version }}-amd64
      - ghcr.io/stieneee/mumble-discord-bridge:{{ .Version }}-arm64
  - name_template: ghcr.io/stieneee/mumble-discord-bridge:{{ .Version }}
    image_templates:
      - ghcr.io/stieneee/mumble-discord-bridge:{{ .Version }}-amd64
      - ghcr.io/stieneee/mumble-discord-bridge:{{ .Version }}-arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^chore"
      - "^ci"
