global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'mdb'
    scrape_interval: 1s
    static_configs:
      - targets: [
        'mumble-discord-bridge:9559',
      ]
