{
 "title": "Mumble-Discord-Bridge",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connected Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mdb_mumble_users_gauge", "legendFormat": "Mumble" },
    { "expr": "mdb_discord_users_gauge", "legendFormat": "Discord" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mdb_mumble_ping", "legendFormat": "Mumble Ping" },
    { "expr": "mdb_discord_latency", "legendFormat": "Discord Heatbeat Latency" }
   ]
  },
  {
   "title": "Mumble to Discord",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(mdb_mumble_received_count[$__rate_interval])",
     "legendFormat": "Mumble Recieved"
    },
    { "expr": "mdb_discord_buffer_gauge", "legendFormat": "To Discord Buffer" },
    {
     "expr": "rate(mdb_discord_sent_count[$__rate_interval])",
     "legendFormat": "Discord Sent"
    },
    {
     "expr": "rate(mdb_to_discord_dropped[$__rate_interval])",
     "legendFormat": "To Discord Dropped"
    }
   ]
  },
  {
   "title": "Discord to Mumble",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(mdb_discord_received_count[$__rate_interval])",
     "legendFormat": "Discord Recieved"
    },
    {
     "expr": "rate(mdb_mumble_sent_count[$__rate_interval])",
     "legendFormat": "Mumble Sent"
    },
    {
     "expr": "rate(mdb_to_mumble_dropped[$__rate_interval])",
     "legendFormat": "To Mumble Dropped"
    }
   ]
  },
  {
   "title": "Mumble Mixer Timer Performance",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(mdb_timer_mumble_mixer_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Discord Send Timer Performance",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(mdb_timer_discord_send_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Discord Mixer Timer Performance",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(mdb_timer_discord_mixer_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "mdb_mumble_streaming_gauge", "legendFormat": "Mumble" },
    { "expr": "mdb_discord_streaming_gauge", "legendFormat": "Discord" }
   ]
  },
  {
   "title": "Start Times",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mdb_bridge_start_time*1000", "legendFormat": "Application Start Time" },
    { "expr": "mdb_bridge_starts_time*1000", "legendFormat": "Current Bridge Start" }
   ]
  },
  {
   "title": "Additional Information",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mdb_bridge_starts_count", "legendFormat": "Bridge Connections" },
    { "expr": "mdb_discord_array_size_gauge", "legendFormat": "Discord Array Size" },
    { "expr": "mdb_to_mumble_array_size_gauge", "legendFormat": "Mumble Array Size" }
   ]
  },
  {
   "title": "Go OS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Go Routines" },
    { "expr": "go_threads", "legendFormat": "OS Threads" }
   ]
  },
  {
   "title": "Go GC Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Application Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "Heap Alloc In Use" },
    { "expr": "go_memstats_sys_bytes", "legendFormat": "System Bytes" }
   ]
  },
  {
   "title": "GC Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "increase(go_gc_duration_seconds_count[$__rate_interval])"
    }
   ]
  }
 ]
}