name: 'CI'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
      - name: Install libopus-dev
        run: sudo apt update && sudo apt-get -y install libopus-dev

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: go-license install
        run: go install github.com/google/go-licenses@latest

      - name: go-license save
        run: go-licenses save ./cmd/mumble-discord-bridge --force --save_path="./dist/LICENSES"

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Run GoReleaser Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser Release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: mdb
          path: dist/*