name: 'CI'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Install libopus-dev zip
        run: sudo apt update && sudo apt-get -y install libopus-dev zip

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: go-license install
        run: go install github.com/google/go-licenses@latest

      - name: go-license save
        run: go-licenses save ./cmd/mumble-discord-bridge --force --save_path="./LICENSES" && zip -r -9 LICENSES.zip ./LICENSES
      
      - name: Run GoReleaser Build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: build --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser Release
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: mdb
          path: dist/*
